In [3]:
import numpy as np
import pandas as pd

df = pd.read_csv('用户数据.csv')
df

    姓名  年龄 性别                     邮箱           电话  城市     职业
0   张伟  28  男   zhangwei@example.com  13800138001  北京  软件工程师
1   李娜  32  女       lina@example.com  13800138002  上海   产品经理
2   王强  25  男  wangqiang@example.com  13800138003  广州  数据分析师
3   刘芳  29  女    liufang@example.com  13800138004  深圳  UI设计师
4   陈杰  35  男    chenjie@example.com  13800138005  杭州    架构师
5   赵敏  27  女    zhaomin@example.com  13800138006  成都   运营经理
6   孙磊  31  男     sunlei@example.com  13800138007  武汉   后端开发
7   周婷  26  女   zhouting@example.com  13800138008  南京   市场专员
8   吴昊  40  男      wuhao@example.com  13800138009  重庆   技术总监
9   郑静  33  女  zhengjing@example.com  13800138010  西安   人力资源
10  钱进  22  男    qianjin@example.com  13800138011  苏州   前端开发
11  马丽  30  女       mali@example.com  13800138012  长沙   财务经理
12  黄波  38  男    huangbo@example.com  13800138013  郑州   项目经理
13  许慧  24  女      xuhui@example.com  13800138014  东莞  测试工程师
14  冯刚  29  男   fenggang@example.com  13800138015  青岛  运维工程师
15  朱红  28  女    zhuhong@example.com  13800138016  合肥   销售经理
16  沈明  36  男   shenming@example.com  13800138017  福州  数据库管理
17  杨雪  27  女    yangxue@example.com  13800138018  厦门   品牌经理
18  林涛  33  男    lin tao@example.com  13800138019  天津  安全工程师
19  何萍  31  女     heping@example.com  13800138020  大连   客服主管

In [5]:
print(df.年龄.mean())

30.2

In [8]:
df = df.tail()
df.to_csv('new.csv')

In [15]:
df = pd.read_json('user_date.json')
print(type(df))
df

<class 'pandas.DataFrame'>

    姓名  年龄 性别                     邮箱           电话  城市     职业
0   张伟  28  男   zhangwei@example.com  13800138001  北京  软件工程师
1   李娜  32  女       lina@example.com  13800138002  上海   产品经理
2   王强  25  男  wangqiang@example.com  13800138003  广州  数据分析师
3   刘芳  29  女    liufang@example.com  13800138004  深圳  UI设计师
4   陈杰  35  男    chenjie@example.com  13800138005  杭州    架构师
5   赵敏  27  女    zhaomin@example.com  13800138006  成都   运营经理
6   孙磊  31  男     sunlei@example.com  13800138007  武汉   后端开发
7   周婷  26  女   zhouting@example.com  13800138008  南京   市场专员
8   吴昊  40  男      wuhao@example.com  13800138009  重庆   技术总监
9   郑静  33  女  zhengjing@example.com  13800138010  西安   人力资源
10  钱进  22  男    qianjin@example.com  13800138011  苏州   前端开发
11  马丽  30  女       mali@example.com  13800138012  长沙   财务经理
12  黄波  38  男    huangbo@example.com  13800138013  郑州   项目经理
13  许慧  24  女      xuhui@example.com  13800138014  东莞  测试工程师
14  冯刚  29  男   fenggang@example.com  13800138015  青岛  运维工程师
15  朱红  28  女    zhuhong@example.com  13800138016  合肥   销售经理
16  沈明  36  男   shenming@example.com  13800138017  福州  数据库管理
17  杨雪  27  女    yangxue@example.com  13800138018  厦门   品牌经理
18  林涛  33  男     lintao@example.com  13800138019  天津  安全工程师
19  何萍  31  女     heping@example.com  13800138020  大连   客服主管

In [18]:
import json
with open('user_date.json') as f:
    data = json.load(f)
print(data)

UnicodeDecodeError: 'gbk' codec can't decode byte 0xb7 in position 52: illegal multibyte sequence