In [62]:
import numpy as np
import pandas as pd
s1 = pd.Series([1, 2, 3, 4])
s2 = pd.Series([5, 6, 7, 8])
s = pd.DataFrame({"第一列": s1, "第二列": s2})
print(s)
s

   第一列  第二列
0    1    5
1    2    6
2    3    7
3    4    8

   第一列  第二列
0    1    5
1    2    6
2    3    7
3    4    8

In [61]:
df = pd.DataFrame(
    {
        # "id": [1, 2, 3, 4],
        "name":['A', 'B', 'C', 'D', 'A'],
        "val":[50, 48, 39, 43, 50],
    }, index = [1, 2, 3, 4, 5], columns = ['name', 'val']
)
df

  name  val
1    A   50
2    B   48
3    C   39
4    D   43
5    A   50

In [14]:
print(df.dtypes)
print(df.shape)
print(df.size)

name      str
val     int64
dtype: object
(4, 2)
8

In [18]:
print(df.T.columns)
df

Index([1, 2, 3, 4], dtype='int64')

  name  val
1    A   50
2    B   48
3    C   39
4    D   43

In [19]:
print(df.loc[2])

name     B
val     48
Name: 2, dtype: object

In [20]:
print(df.iloc[2])

name     C
val     39
Name: 3, dtype: object

In [24]:
print(df.loc[:, 'val'])
print(df.iloc[:, 0])

1    50
2    48
3    39
4    43
Name: val, dtype: int64
1    A
2    B
3    C
4    D
Name: name, dtype: str

In [29]:
print(df.at[2, 'val'])
print(df.iat[2, 0])
print(df.loc[2, 'val'])
print(df.iloc[2, 0])

48
C
48
C

In [33]:
print(df['name'])
print(df.val)
print(df[['name', 'val']])

1    A
2    B
3    C
4    D
Name: name, dtype: str
1    50
2    48
3    39
4    43
Name: val, dtype: int64
  name  val
1    A   50
2    B   48
3    C   39
4    D   43

In [35]:
print(df.head(2))
print(df.tail(2))

  name  val
1    A   50
2    B   48
  name  val
3    C   39
4    D   43

In [39]:
df[df.val > 45]
df[(df.val > 45) & (df.name < 'B')]

  name  val
1    A   50

In [44]:
print(df.sample(2))
df.sample(2)

  name  val
2    B   48
4    D   43

  name  val
1    A   50
2    B   48

In [48]:
print(df.isin(['C', 50]))

    name    val
1  False   True
2  False  False
3   True  False
4  False  False

In [49]:
print(df.isna())

    name    val
1  False  False
2  False  False
3  False  False
4  False  False

In [60]:
print(df['val'].sum())
print(df.val.sum())
print(df.val.mean())
print(df.val.mode()) #众数
print(df.val.quantile(0.25)) #分位数
print(df.describe())

180
180
45.0
0    39
1    43
2    48
3    50
Name: val, dtype: int64
42.0
             val
count   4.000000
mean   45.000000
std     4.966555
min    39.000000
25%    42.000000
50%    45.500000
75%    48.500000
max    50.000000

In [63]:
print(df.value_counts())

name  val
A     50     2
B     48     1
C     39     1
D     43     1
Name: count, dtype: int64

In [64]:
print(df.drop_duplicates)

<bound method DataFrame.drop_duplicates of   name  val
1    A   50
2    B   48
3    C   39
4    D   43
5    A   50>

In [66]:
print(df.duplicated(subset = ['val']))

1    False
2    False
3    False
4    False
5     True
dtype: bool

In [69]:
print(df.cumsum()) #累计
print(df.cummin())
print(df.cummax())

    name  val
1      A   50
2     AB   98
3    ABC  137
4   ABCD  180
5  ABCDA  230
  name  val
1    A   50
2    A   48
3    A   39
4    A   39
5    A   39
  name  val
1    A   50
2    B   50
3    C   50
4    D   50
5    D   50

In [72]:
print(df.sort_index(ascending = False))

  name  val
5    A   50
4    D   43
3    C   39
2    B   48
1    A   50

In [74]:
print(df.sort_values(by = 'val'))

  name  val
3    C   39
4    D   43
2    B   48
1    A   50
5    A   50

In [78]:
print(df.sort_values(by = ['val', 'name'], ascending = False))  #按..排列

  name  val
1    A   50
5    A   50
2    B   48
4    D   43
3    C   39

In [80]:
print(df.nlargest(3, columns = ['val']))

  name  val
1    A   50
5    A   50
2    B   48