**数值的缺失**

In [52]:
import pandas as pd
import numpy as np

s = pd.Series([1, 2, np.nan, None, pd.NA])
# print(s)
print(s.isna())
print(s.isnull())

0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool

In [53]:
df = pd.DataFrame([[1, pd.NA, 2], [2, 3, 4], [None, 4, 5]], columns = ['第一列', '第二列', '第三列'], index = [1, 2, 3])
print(df.isna())

     第一列    第二列    第三列
1  False   True  False
2  False  False  False
3   True  False  False

In [69]:
#查看缺失值数量
print(df.isna().sum())  
print(df.isna().sum(axis = 1))

UserID          0
FirstName     169
LastName      178
Email         162
Phone         152
Country       161
City          148
Age           157
SignupDate    151
Status        149
Score         145
dtype: int64
0      4
1      4
2      3
3      2
4      2
      ..
495    3
496    2
497    4
498    4
499    4
Length: 500, dtype: int64

**剔除缺失值 dropna（）**

In [55]:
print(s.dropna())

0    1
1    2
dtype: object

In [56]:
print(df.dropna())  #有缺失值就剔除

   第一列 第二列  第三列
2  2.0   3    4

In [57]:
print(df.dropna(how = 'all'))  #所有都缺失才剔除

   第一列   第二列  第三列
1  1.0  <NA>    2
2  2.0     3    4
3  NaN     4    5

In [58]:
print(df.dropna(thresh = 2))  #至少有n个数据保留

   第一列   第二列  第三列
1  1.0  <NA>    2
2  2.0     3    4
3  NaN     4    5

In [59]:
print(df.dropna(axis = 1))

   第三列
1    2
2    4
3    5

In [60]:
print(df.dropna(subset = ['第二列'])) #保留第二列存在的值

   第一列 第二列  第三列
2  2.0   3    4
3  NaN   4    5

**缺失值的填充**

In [61]:
df = pd.read_csv('users_data.csv')
df.isna().sum(axis = 0)
print(df.head())

  UserID FirstName LastName                          Email            Phone  \
0  U0001    Elijah      NaN                            NaN  +1-357-175-1007
1  U0002       NaN      NaN  david.williams497@hotmail.com  +1-952-142-7088
2  U0003    Joseph      NaN      joseph.davis964@yahoo.com  +1-551-185-8562
3  U0004  Isabella      NaN                            NaN  +1-249-307-6236
4  U0005     Ethan      NaN    ethan.martin824@outlook.com  +1-700-258-8891

          Country     City   Age  SignupDate     Status  Score
0          France   Berlin   NaN  2024-06-25     Active    NaN
1          Canada    Tokyo   NaN         NaN  Suspended   66.6
2  United Kingdom      NaN  54.0  2020-02-24        NaN   30.6
3          Canada  Houston  26.0  2021-08-08     Active   61.2
4          Brazil     Lyon   NaN  2025-12-20   Inactive   18.0

In [62]:
print(df.fillna({'Score': 88.8, 'City': 'Hangzhou'})) #把Score和City里缺失的数值都变成88.8和Hangzhou

    UserID FirstName  LastName                             Email  \
0    U0001    Elijah       NaN                               NaN
1    U0002       NaN       NaN     david.williams497@hotmail.com
2    U0003    Joseph       NaN         joseph.davis964@yahoo.com
3    U0004  Isabella       NaN                               NaN
4    U0005     Ethan       NaN       ethan.martin824@outlook.com
..     ...       ...       ...                               ...
495  U0496      Liam       NaN                               NaN
496  U0497     Lucas  Anderson  lucas.anderson133@protonmail.com
497  U0498   William       NaN                               NaN
498  U0499       NaN  Anderson                               NaN
499  U0500    Evelyn     Brown                               NaN

               Phone         Country      City   Age  SignupDate     Status  \
0    +1-357-175-1007          France    Berlin   NaN  2024-06-25     Active
1    +1-952-142-7088          Canada     Tokyo   NaN         NaN  Suspended
2    +1-551-185-8562  United Kingdom  Hangzhou  54.0  2020-02-24        NaN
3    +1-249-307-6236          Canada   Houston  26.0  2021-08-08     Active
4    +1-700-258-8891          Brazil      Lyon   NaN  2025-12-20   Inactive
..               ...             ...       ...   ...         ...        ...
495  +1-710-576-6917          Brazil   Houston  23.0  2022-04-08        NaN
496  +1-248-861-8482   United States  Hangzhou   NaN  2025-10-28     Active
497              NaN           India  Hangzhou  18.0  2025-07-19   Inactive
498              NaN          France   Phoenix  23.0         NaN  Suspended
499  +1-242-186-2878             NaN    Sydney   NaN  2025-06-18        NaN

     Score
0     88.8
1     66.6
2     30.6
3     61.2
4     18.0
..     ...
495   49.3
496   32.8
497   26.0
498   85.4
499   45.6

[500 rows x 11 columns]

In [63]:
print(df.fillna(df[['Age', 'Score']].mean()))  #使用平均值去填充NaN（统计值）

    UserID FirstName  LastName                             Email  \
0    U0001    Elijah       NaN                               NaN
1    U0002       NaN       NaN     david.williams497@hotmail.com
2    U0003    Joseph       NaN         joseph.davis964@yahoo.com
3    U0004  Isabella       NaN                               NaN
4    U0005     Ethan       NaN       ethan.martin824@outlook.com
..     ...       ...       ...                               ...
495  U0496      Liam       NaN                               NaN
496  U0497     Lucas  Anderson  lucas.anderson133@protonmail.com
497  U0498   William       NaN                               NaN
498  U0499       NaN  Anderson                               NaN
499  U0500    Evelyn     Brown                               NaN

               Phone         Country     City        Age  SignupDate  \
0    +1-357-175-1007          France   Berlin  43.653061  2024-06-25
1    +1-952-142-7088          Canada    Tokyo  43.653061         NaN
2    +1-551-185-8562  United Kingdom      NaN  54.000000  2020-02-24
3    +1-249-307-6236          Canada  Houston  26.000000  2021-08-08
4    +1-700-258-8891          Brazil     Lyon  43.653061  2025-12-20
..               ...             ...      ...        ...         ...
495  +1-710-576-6917          Brazil  Houston  23.000000  2022-04-08
496  +1-248-861-8482   United States      NaN  43.653061  2025-10-28
497              NaN           India      NaN  18.000000  2025-07-19
498              NaN          France  Phoenix  23.000000         NaN
499  +1-242-186-2878             NaN   Sydney  43.653061  2025-06-18

        Status      Score
0       Active  51.277746
1    Suspended  66.600000
2          NaN  30.600000
3       Active  61.200000
4     Inactive  18.000000
..         ...        ...
495        NaN  49.300000
496     Active  32.800000
497   Inactive  26.000000
498  Suspended  85.400000
499        NaN  45.600000

[500 rows x 11 columns]

In [64]:
print(df.ffill()) #front用前面的相邻值填充

    UserID FirstName  LastName                             Email  \
0    U0001    Elijah       NaN                               NaN
1    U0002    Elijah       NaN     david.williams497@hotmail.com
2    U0003    Joseph       NaN         joseph.davis964@yahoo.com
3    U0004  Isabella       NaN         joseph.davis964@yahoo.com
4    U0005     Ethan       NaN       ethan.martin824@outlook.com
..     ...       ...       ...                               ...
495  U0496      Liam   Ramirez  jennifer.martinez154@outlook.com
496  U0497     Lucas  Anderson  lucas.anderson133@protonmail.com
497  U0498   William  Anderson  lucas.anderson133@protonmail.com
498  U0499   William  Anderson  lucas.anderson133@protonmail.com
499  U0500    Evelyn     Brown  lucas.anderson133@protonmail.com

               Phone         Country     City   Age  SignupDate     Status  \
0    +1-357-175-1007          France   Berlin   NaN  2024-06-25     Active
1    +1-952-142-7088          Canada    Tokyo   NaN  2024-06-25  Suspended
2    +1-551-185-8562  United Kingdom    Tokyo  54.0  2020-02-24  Suspended
3    +1-249-307-6236          Canada  Houston  26.0  2021-08-08     Active
4    +1-700-258-8891          Brazil     Lyon  26.0  2025-12-20   Inactive
..               ...             ...      ...   ...         ...        ...
495  +1-710-576-6917          Brazil  Houston  23.0  2022-04-08   Inactive
496  +1-248-861-8482   United States  Houston  23.0  2025-10-28     Active
497  +1-248-861-8482           India  Houston  18.0  2025-07-19   Inactive
498  +1-248-861-8482          France  Phoenix  23.0  2025-07-19  Suspended
499  +1-242-186-2878          France   Sydney  23.0  2025-06-18  Suspended

     Score
0      NaN
1     66.6
2     30.6
3     61.2
4     18.0
..     ...
495   49.3
496   32.8
497   26.0
498   85.4
499   45.6

[500 rows x 11 columns]

In [65]:
print(df.bfill()) #back用后面的相邻值填充

    UserID FirstName  LastName                             Email  \
0    U0001    Elijah  Robinson     david.williams497@hotmail.com
1    U0002    Joseph  Robinson     david.williams497@hotmail.com
2    U0003    Joseph  Robinson         joseph.davis964@yahoo.com
3    U0004  Isabella  Robinson       ethan.martin824@outlook.com
4    U0005     Ethan  Robinson       ethan.martin824@outlook.com
..     ...       ...       ...                               ...
495  U0496      Liam  Anderson  lucas.anderson133@protonmail.com
496  U0497     Lucas  Anderson  lucas.anderson133@protonmail.com
497  U0498   William  Anderson                               NaN
498  U0499    Evelyn  Anderson                               NaN
499  U0500    Evelyn     Brown                               NaN

               Phone         Country     City   Age  SignupDate     Status  \
0    +1-357-175-1007          France   Berlin  54.0  2024-06-25     Active
1    +1-952-142-7088          Canada    Tokyo  54.0  2020-02-24  Suspended
2    +1-551-185-8562  United Kingdom  Houston  54.0  2020-02-24     Active
3    +1-249-307-6236          Canada  Houston  26.0  2021-08-08     Active
4    +1-700-258-8891          Brazil     Lyon  64.0  2025-12-20   Inactive
..               ...             ...      ...   ...         ...        ...
495  +1-710-576-6917          Brazil  Houston  23.0  2022-04-08     Active
496  +1-248-861-8482   United States  Phoenix  18.0  2025-10-28     Active
497  +1-242-186-2878           India  Phoenix  18.0  2025-07-19   Inactive
498  +1-242-186-2878          France  Phoenix  23.0  2025-06-18  Suspended
499  +1-242-186-2878             NaN   Sydney   NaN  2025-06-18        NaN

     Score
0     66.6
1     66.6
2     30.6
3     61.2
4     18.0
..     ...
495   49.3
496   32.8
497   26.0
498   85.4
499   45.6

[500 rows x 11 columns]

**数据的重复**

In [66]:
# import pandas as pd
data = {
    "name": ['A', 'B', 'A', 'D', 'A', 'B'],
    "age": [1, 2, 3, 4, 1, 2],
    "city": ['Y', 'Y', 'S', 'S', 'Y', 'Y']
}
ss = pd.DataFrame(data)
ss

  name  age city
0    A    1    Y
1    B    2    Y
2    A    3    S
3    D    4    S
4    A    1    Y
5    B    2    Y

In [67]:
ss.duplicated()  #检查重复行

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [68]:
ss.drop_duplicates() #去除重复的数据

  name  age city
0    A    1    Y
1    B    2    Y
2    A    3    S
3    D    4    S

In [72]:
ss.drop_duplicates(subset = ['name']) #去除name重复的数据

  name  age city
0    A    1    Y
1    B    2    Y
3    D    4    S