In [20]:
import pandas as pd
data = {
    'ID': [1, 2], 
    'name': ['A', 'B'],
    'English': [60, 70],
    'Math': [70, 60],
    'Science': [70, 80]
}
df = pd.DataFrame(data)
df.T

          0   1
ID        1   2
name      A   B
English  60  70
Math     70  60
Science  70  80

In [21]:
df2 = pd.melt(df, id_vars = ['ID', 'name'], var_name = '科目', value_name = '分数')  #宽表转换成长表

In [22]:
df2.sort_values('name')  #按名字排序

   ID name       科目  分数
0   1    A  English  60
2   1    A     Math  70
4   1    A  Science  70
1   2    B  English  70
3   2    B     Math  60
5   2    B  Science  80

In [23]:
pd.pivot(df2, index=['ID', 'name'], columns = '科目', values = '分数') #长转宽

科目       English  Math  Science
ID name
1  A          60    70       70
2  B          70    60       80

In [27]:
data = {
    'ID': [1, 2], 
    'name': ['A AA', 'B BB'],
    'English': [60, 70],
    'Math': [70, 60],
    'Science': [70, 80]
}
df = pd.DataFrame(data)
df[['first', 'last']] = df['name'].str.split(' ', expand = True)
df

   ID  name  English  Math  Science first last
0   1  A AA       60    70       70     A   AA
1   2  B BB       70    60       80     B   BB

In [37]:
s = pd.read_csv('users_data.csv')
s.head()

,UserID,FirstName,LastName,Email,Phone,Country,City,Age,SignupDate,Status,Score
0,U0001,Elijah,NaN,NaN,+1-357-175-1007,France,Berlin,NaN,2024-06-25,Active,NaN
1,U0002,NaN,NaN,david.williams497@hotmail.com,+1-952-142-7088,Canada,Tokyo,NaN,NaN,Suspended,66.6
2,U0003,Joseph,NaN,joseph.davis964@yahoo.com,+1-551-185-8562,United Kingdom,NaN,54.0,2020-02-24,NaN,30.6
3,U0004,Isabella,NaN,NaN,+1-249-307-6236,Canada,Houston,26.0,2021-08-08,Active,61.2
4,U0005,Ethan,NaN,ethan.martin824@outlook.com,+1-700-258-8891,Brazil,Lyon,NaN,2025-12-20,Inactive,18.0

In [38]:
s = s[['Score', 'UserID']]
s

     Score UserID
0      NaN  U0001
1     66.6  U0002
2     30.6  U0003
3     61.2  U0004
4     18.0  U0005
..     ...    ...
495   49.3  U0496
496   32.8  U0497
497   26.0  U0498
498   85.4  U0499
499   45.6  U0500

[500 rows x 2 columns]

In [42]:
s.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Score   355 non-null    float64
 1   UserID  500 non-null    str
dtypes: float64(1), str(1)
memory usage: 7.9 KB

In [46]:
s['Score'] = s['Score'].astype('float32')
s.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Score   355 non-null    float32
 1   UserID  500 non-null    str
dtypes: float32(1), str(1)
memory usage: 6.0 KB